# Example PlatformIO Project Configuration Override
# ------------------------------------------------------------------------------
# Copy to platformio_override.ini to activate overrides
# ------------------------------------------------------------------------------
# Please visit documentation: https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32_4MB_M

[env:esp32_4MB_M_base]
extends = esp32_4MB_S_base
upload_speed = 921600
build_unflags = ${esp32_4MB_S_base.build_unflags}
build_flags = ${common.build_flags_esp32}  ${common_mm.build_flags_S}  ${common_mm.build_flags_M} 
  -D WLED_RELEASE_NAME=ESP32
  -D WLED_DISABLE_BROWNOUT_DET
  -D WLED_USE_MY_CONFIG    
  -D USERMOD_ANIMATED_STAIRCASE
lib_deps = ${esp32_4MB_S_base.lib_deps} ${common_mm.lib_deps_M}